version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: erp_vet_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_docker
      POSTGRES_PASSWORD: password_docker
      POSTGRES_DB: erp_vet_agro
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: